services:
  # Web Service pentru Django + Daphne (HTTP + WebSocket)
  - type: web
    name: xo-game
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT xo_game.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: xo-game-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: xo-game-redis
          property: connectionString

  # Redis pentru Channel Layers (WebSocket)
  - type: redis
    name: xo-game-redis
    region: frankfurt
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []

# PostgreSQL Database
databases:
  - name: xo-game-db
    region: frankfurt
    plan: free
    databaseName: xo_game
    user: xo_game_user

