# Generated by Django 5.0 on 2025-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('player_x', models.CharField(blank=True, max_length=255, null=True)),
                ('player_o', models.CharField(blank=True, max_length=255, null=True)),
                ('board', models.JSONField(default=list)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, default='', max_length=10)),
                ('score_x', models.IntegerField(default=0)),
                ('score_o', models.IntegerField(default=0)),
                ('score_draws', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
